package com.nexalink.nearby.model

/**
 * Represents an advertised device discovered in proximity.
 *
 * @property endpointId Unique identifier generated by Nearby Connections for this device session.
 * @property endpointName Human-readable display name advertised by the peer (e.g., "Alice's Phone").
 */
data class DiscoveredDevice(
    val endpointId: String,
    val endpointName: String
)
